# Site settings
title: Joshua Ling
description: ''
url: 'https://joshlingaround.com'

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name: Joshua Ling
  url: https://joshlingaround.com
  email: joshling1919@gmail.com

# Build settings
markdown: kramdown
include:
  - _pages

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink: /:year-:month-:day/:title
paginate: 5
